### ISSUE TITLE
Create a base CSS file

### ISSUE THREAD

**Issue by emilhaugberg** [psovea/frontend#10]
We want to create a base CSS file that defines the following:

- base first color
- base secondary color
- etc.

**Comment by ericwoude** [comment]
After fiddling around on this color palette create website I got this palette which I liked.
![color-palette](https://user-images.githubusercontent.com/12992410/58898603-35db7980-86fb-11e9-93a0-7edf76cf0182.png)

Maybe we could try to emulate the look and feel of [this](http://preview.themeforest.net/item/easypro-developer-friendly-react-bootstrap-4-admin-template/full_screen_preview/21798550?ref=cirvitis&clickthrough_id=1407728439&redirect_back=true) dashboard; light colours for the background and the orangy color of the palette for display in charts and other important things we like to put emphasis on.
