### ISSUE TITLE
Implement grid system

### ISSUE THREAD

**Issue by emilhaugberg** [psovea/frontend#9]
As noted in #8, we want a grid system for our webapp.

![Amazing Diagram](https://user-images.githubusercontent.com/12992410/58886882-e68a4e80-86e4-11e9-8a18-b0637d53f5d9.png)
)

**Comment by ericwoude** [comment]
You could use the [grid](https://jenil.github.io/chota/#grid) which is provided by Chota to implement the blocks

**Comment by ericwoude** [comment]
Implemented in #22
